spring:
  application:
    name: eureka-server
server:
  port: 8888
eureka:
  instance:
    hostname: 192.168.3.197
  client:
    service-url:
      defaultZone: http://192.168.3.197:8888/eureka/
    fetch-registry: false
    register-with-eureka: false
